# Antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
# Theme
antigen theme dst
antigen apply

# Share history
setopt histignorealldups sharehistory
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
TERM=xterm-256color

# Edit long command
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e
bindkey "^[h" backward-kill-word

# Use modern completion system
autoload -Uz compinit
compinit

# Editors for emacs and p4
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient --alternate-editor='' -t"
export P4EDITOR="${EDITOR}"
export P4DIFF="colordiff -u"

# Alias
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'
alias i="ipython --no-confirm-exit"
alias m="${EDITOR}"
alias sn="screen -S"
alias sr="screen -rd"

# Autojump
source /usr/share/autojump/autojump.zsh
